[package]
name = "mp3"
version = "0.0.1"
edition = "2024"

[dependencies]
# Cortex-M 
cortex-m = "0.7.7"
cortex-m-rt = "0.7.5"

# Panic Handler
panic-probe = { version = "1.0.0",  features = ["print-defmt"]}

# Embassy
embassy-executor = { version = "0.9", features = [
  "arch-cortex-m",
  "executor-thread",
  "defmt"
] }
embassy-time = { version = "0.5.0", features =  ["defmt", "defmt-timestamp-uptime"]}
embassy-rp = { version = "0.10.0", features = [
"defmt", "time-driver", "critical-section-impl", "rp235xa", "binary-info"
] }
embassy-usb-logger = "0.5.1"
embassy-sync = { version = "0.8.0", features = ["defmt"] }
embassy-net = { version = "0.9.0", features = ["defmt", "icmp", "tcp", "udp", "raw", "dhcpv4", "medium-ethernet", "dns", "proto-ipv4", "proto-ipv6", "multicast"] }
embedded-io-async = { version = "0.7.0", features = ["defmt"] }
#embassy-net-driver = { version = "0.2.0", features = ["defmt"] }
#embassy-net-driver-channel = { version = "0.4.0", features = ["defmt"] }
#embedded-io-async = { version = "0.7.0", features = ["defmt"] }
#embedded-hal-async = "1.0"
#embassy-usb-logger = "0.5.1"
#embassy-embedded-hal = { version ="0.6.0", features = ["defmt"] }

log = "0.4"
defmt = "1.0.1"
defmt-rtt = "1.1.0"
static_cell = "2.1.1"
embassy-futures = { version =  "0.1.2", features = ["defmt"] }
cyw43 = { version = "0.7.0", features = ["defmt"]}
cyw43-pio = { version =  "0.10.0", features = ["defmt"] }
nanomp3 = "0.1.1"


