[package]
name = "core1"
version = "0.0.1"
edition = "2024"

[dependencies]
cortex-m = "0.7.2"
cortex-m-rt = "0.7"
embassy-executor = { 
    version = "0.10.0", 
    features = [
        "platform-cortex-m",
        "executor-thread",
        #  "executor-interrupt"
    ],
    path = "../embassy/embassy-executor"
}
embassy-rp = { 
    version = "0.10.0", 
    default-features = false, 
    features = ["rt", "multicore", "rp235xa", "critical-section-impl", "imagedef-secure-exe",
    "time-driver"],
    path = "../embassy/embassy-rp"
}
embassy-time = {
    version = "0.5.1",
    path = "../embassy/embassy-time"
}
embassy-usb-logger = {
    version = "0.6.0",
    path = "../embassy/embassy-usb-logger"
}
embassy-net = {
    version = "0.9.0",
    features = ["icmp", "tcp", "udp", "raw", "dhcpv4", "medium-ethernet", "dns", "proto-ipv4", "proto-ipv6", "multicast"],
    path = "../embassy/embassy-net"
}
cyw43 = { 
    version = "0.7.0",
    path = "../embassy/cyw43"
}
cyw43-pio = { 
    version = "0.10.0",
    path = "../embassy/cyw43-pio"
}
log = "0.4.32"
static_cell = "2.1.1"
critical-section = "1.2.0"
rp-pac = { version = "7.0.0" }
nanomp3 = "0.1.1"
embedded-io-async = "0.7.0"
#rp235x-hal = "0.4.0"

[features]
spinlock = []
fifo = []
